name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Run Script 1
        run: echo script-1-message of job 1

      - name: Run Script 2 
        run: |
          echo script-2.1-message of job 1
          echo script-2.1-message of job 1

  job-2:
    runs-on: ubuntu-latest

    needs: [job-1]

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Run Script 1 of job 2
        run: echo script-1-message of job 2

      - name: Run Script 2 
        run: |
          echo script-2.1-message of job 2
          echo script-2.1-message of job 2
